SELECT UG.USER_ID,	UG.NICKNAME, UB.TOTAL_SALES
FROM USED_GOODS_USER UG
JOIN (
    SELECT WRITER_ID AS USER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE' 
    GROUP BY USER_ID
    HAVING TOTAL_SALES >= 700000
) AS UB ON UG.USER_ID = UB.USER_ID
ORDER BY UB.TOTAL_SALES ASC;