SELECT 
    EXTRACT(HOUR FROM DATETIME) AS HOUR, 
    COUNT(*) AS COUNT 
FROM ANIMAL_OUTS 
WHERE EXTRACT(HOUR FROM DATETIME) >= 9 AND EXTRACT(HOUR FROM DATETIME) <= 19
GROUP BY EXTRACT(HOUR FROM DATETIME)
ORDER BY HOUR;

-- https://chat.openai.com/share/fadf86f5-a690-4b46-940c-a3620e02b79f