SELECT MCDP_CD AS 진료과코드, COUNT(DISTINCT APNT_NO) AS 5월예약건수
FROM APPOINTMENT
WHERE APNT_YMD >= '2022-05-01' AND APNT_YMD < '2022-06-01'
# AND (APNT_CNCL_YN IS NULL OR APNT_CNCL_YN != 'Y')
GROUP BY MCDP_CD
ORDER BY COUNT(DISTINCT APNT_NO), MCDP_CD;