-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF AS FH
JOIN(
    SELECT * FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'fruit_based'
)AS II
WHERE FH.FLAVOR = II.FLAVOR
AND FH.TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;
