-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID,	TITLE, PRICE,        CASE 
           WHEN STATUS = 'DONE' THEN '거래완료'
           WHEN STATUS = 'RESERVED' THEN '예약중'
           WHEN STATUS = 'SALE' THEN '판매중'
           ELSE STATUS
       END AS STATUSSTATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE >= "2022-10-05 00:00:00"
AND  CREATED_DATE < "2022-10-06 00:00:00"
ORDER BY BOARD_ID DESC
;