SELECT B.CATEGORY, SUM(BS.TOTAL_SALES) AS TOTAL_SALES 
FROM BOOK B
JOIN (
    SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES  
    FROM BOOK_SALES
    WHERE SALES_DATE >= '2022-01-01 00:00:00'
    AND SALES_DATE < '2022-02-01 00:00:00'
    GROUP BY BOOK_ID
) AS BS ON B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
