name: File Count and Update README

on:
  push:
  workflow_dispatch:

jobs:
  count_files_and_update_readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Count Files and Update README
        run: |
          # 파일 수 계산
          java_count=$(find . -type f -name "*.java" | wc -l)
          sql_count=$(find . -type f -name "*.sql" | wc -l)
          undefined_count=$(find . -type f -not -name "*.*" | wc -l)
          total_files=$(find . -type f | wc -l)
          java_ratio=$(echo "scale=2; $java_count/$total_files*100" | bc)
          sql_ratio=$(echo "scale=2; $sql_count/$total_files*100" | bc)
          undefined_ratio=$(echo "scale=2; $undefined_count/$total_files*100" | bc)

          # README 업데이트
          sed -i "/<!-- file_counts_start -->/,/<!-- file_counts_end -->/c\<!-- file_counts_start -->\nJava files: $java_count ($java_ratio%)\nSQL files: $sql_count ($sql_ratio%)\nUndefined files: $undefined_count ($undefined_ratio%)\n<!-- file_counts_end -->" README.md

      - name: Commit and Push README Updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update file counts in README"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
